# Generated by Django 6.0.7 on 2026-08-02 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.PositiveIntegerField(default=0, help_text='زمان تخمینی به دقیقه'),
        ),
        migrations.AddField(
            model_name='task',
            name='time_spent',
            field=models.PositiveIntegerField(default=0, help_text='زمان صرف شده به دقیقه'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('LOW', 'کم'), ('MEDIUM', 'متوسط'), ('HIGH', 'بالا')], default='MEDIUM', max_length=10),
        ),
    ]
